server:
  port: 18000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/members/**
        - id: instance-service
          uri: lb://INSTANCE-SERVICE
          predicates:
            - Path=/instances/**
eureka:
  instance:
    instance-id: gateway-microservice
  client:
    fetch-registry: true # ??? ????? ???
    register-with-eureka: true # ??? ????? ???
    service-url:
      defaultZone: http://localhost:18081/eureka

