server:
  port: 18002

spring:
  profiles:
    active: test
  application:
    name: instance-service
  #  config:
  #    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      #      url: http://localhost:8888/
      name: member-service

# cloud config actuator endpoints 활성화


eureka:
  instance:
    instance-id: instance-microservice
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
