server:
  port: 18002

spring:
  application:
    name: instance-service

eureka:
  instance:
    instance-id: instance-microservice
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:18081/eureka
