server:
  port: 18001

spring:
  profiles:
    active: test
  application:
    name: member-service
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
#      url: http://localhost:8888/
      name: member-service

# cloud config actuator endpoints 활성화


eureka:
  instance:
    instance-id: member-microservice
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
